version: '3.8'

services:
  #frontend VUE 3
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: npm run dev --host
    networks:
      - app-lv

  #backend Laravel 10
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    volumes:
      - ./backend:/var/www
    depends_on:
      - db
    ports:
      - "82:8000"
    env_file:
      - ./backend/.env
    networks:
      - app-lv

  db:
    image: mysql:8.0
    volumes:
      - ./docker/db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: treinamento
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3333:3306"
    networks:
      - app-lv

networks:
  app-lv:
    driver: bridge

volumes:
  db-data:
